import type { NewsCategory, SourceConfig } from "./types";

/** WordPress / RSS category strings → app buckets */
const HKCM_MAP: Record<string, NewsCategory> = {
  本地時事: "本地",
  立法會: "本地",
  區議會: "本地",
  國際議題: "國際",
  新聞: "時事",
  國際: "國際",
};

const GREENBEAN_MAP: Record<string, NewsCategory> = {
  時事: "時事",
  兩邊走走: "時事",
  英國這邊事: "國際",
  國際多Bean事: "國際",
  小島大風吹: "本地",
  數說香港: "本地",
  其他熱話: "時事",
  人物實錄: "其他",
  記香港人: "其他",
  知識生活: "其他",
  專欄: "其他",
  法律搞Bean科: "其他",
  精選推介: "時事",
};

/** Liber Research (WordPress) — mostly HK research; extend keys if RSS adds new slugs */
const LIBER_MAP: Record<string, NewsCategory> = {
  土地供應: "本地",
  市區重建: "本地",
  房屋研究: "本地",
  北部都會區: "本地",
  土地及房屋研究: "本地",
  土地規劃基建: "本地",
  規劃研究: "本地",
  丁屋研究: "本地",
  濕地研究: "本地",
  專題研究: "本地",
  簡約公屋: "本地",
  社區研究: "本地",
  社區空間研究: "本地",
  環境保育研究: "本地",
  生態旅遊: "本地",
  郊野公園: "本地",
  古蹟保育研究: "本地",
  數據研究: "本地",
  數據百用: "本地",
  研究資訊: "本地",
  檔案研究: "本地",
  鄉郊: "本地",
  商店空置: "本地",
  解鎖研究: "本地",
  探熱專題: "本地",
  "土地、規劃及基建研究": "本地",
  香港: "本地",
  香港郊野: "本地",
  旅行: "國際",
  旅游: "國際",
  傳媒報導: "時事",
  "In the press": "時事",
  精選: "其他",
  小紅書: "其他",
};

/** 《大學線》CUHK 學生刊物 — WordPress RSS category tags → buckets */
const UBEAT_MAP: Record<string, NewsCategory> = {
  政經國際: "時事",
  中國線: "時事",
  封面故事: "時事",
  採訪手記: "時事",
  新秀新論: "時事",
  大學線專欄: "時事",
  傳媒多面體: "時事",
  人權聚焦: "時事",
  弱勢權益: "時事",
  勞工權益: "時事",
  "LGBTQ+": "時事",
  校園教育: "時事",
  社協: "時事",
  社工: "時事",
  無家者: "時事",
  宏福苑安置: "本地",
  宏福苑: "本地",
  大火: "本地",
  安置: "本地",
  大埔: "本地",
  東壩: "本地",
  破邊洲: "本地",
  主教山: "本地",
  主教山僭建: "本地",
  深水埗主教山: "本地",
  深水埗主教山配水庫: "本地",
  房屋規劃: "本地",
  生態旅遊: "其他",
  過度旅遊: "其他",
  環境保育: "其他",
  冬奧: "國際",
  海外來鴻: "國際",
  人物專訪: "其他",
  焦點人物: "其他",
  文化潮流: "其他",
  文化藝術: "其他",
  消費潮流: "其他",
  生活消費: "其他",
  商業空間: "其他",
  醫療健康: "其他",
  網絡世界: "其他",
  創新科技: "其他",
  動物資訊: "其他",
  體壇故事: "其他",
  體育: "其他",
  抱石: "其他",
  攀石: "其他",
  播映權: "其他",
  特設銷售計劃: "其他",
  當年今日: "其他",
  Podcast: "其他",
  圖片故事: "其他",
};

/** 集誌社 thecollectivehk.com — WordPress RSS `<category>` → buckets */
const COLLECTIVE_MAP: Record<string, NewsCategory> = {
  深度: "時事",
  聚焦一周: "時事",
  新聞自由: "時事",
  立法會選舉: "時事",
  圖解新聞: "時事",
  互動圖解: "時事",
  yahoo新聞: "時事",
  宏福苑: "本地",
  宏福苑火災: "本地",
  獨立委員會: "本地",
  關愛隊: "本地",
  關愛隊工作報告: "本地",
  支聯會案: "時事",
  鄒幸彤: "時事",
  關振邦: "其他",
  白票: "時事",
  廢票: "時事",
  台灣: "國際",
  圖輯: "其他",
  影像: "其他",
};

export const HK_NEWS_FEEDS: SourceConfig[] = [
  /** 放前：合併後 `enrichArticlesWithOgImages` 配額唔會永遠輪唔到獨媒 */
  {
    name: "獨立媒體",
    urls: ["https://www.inmediahk.net/rss.xml"],
    categoryMap: {},
    defaultCategory: "時事",
    inmediaPathCategory: true,
  },
  {
    name: "香城公民媒體",
    urls: ["https://hkcitizenmedia.com/feed/"],
    categoryMap: HKCM_MAP,
    defaultCategory: "其他",
  },
  {
    name: "綠豆 Green Bean Media",
    urls: ["https://greenbean.media/feed/"],
    categoryMap: GREENBEAN_MAP,
    defaultCategory: "其他",
  },
  {
    name: "本土研究社 Liber Research",
    urls: ["https://liber-research.com/feed/"],
    categoryMap: LIBER_MAP,
    defaultCategory: "其他",
    wordpressFeaturedFallback: true,
  },
  {
    name: "大學線",
    urls: ["https://ubeat.com.cuhk.edu.hk/feed/"],
    categoryMap: UBEAT_MAP,
    defaultCategory: "時事",
    wordpressFeaturedFallback: true,
  },
  {
    name: "集誌社",
    urls: ["https://thecollectivehk.com/feed/"],
    categoryMap: COLLECTIVE_MAP,
    defaultCategory: "時事",
    wordpressFeaturedFallback: true,
  },
];
